language: go
go:
- 1.20

services:
- docker

before_install:
- go install -v github.com/mattn/goveralls@latest
# Install dependencies, including test dependencies.
- sudo apt-get update
- go get -v -t ./...

script:
# Vet the code, build the code, and run all the tests.
#- go get -u ./...
#-go vet ./...
#- CGO_ENABLED=0 go build ./...
#- go test ./... -race
#- go test ./... -v -coverprofile=_coverage.cov
- docker build -f Dockerfile.testing -t local-bigquery-testing .
- docker run -it local-bigquery-testing


after_success:
# Coveralls
# Upload coverage information for unit tests.
- $HOME/gopath/bin/goveralls -coverprofile=_coverage.cov -service=travis-ci
