language: go
go:
- 1.20

services:
- docker

env:
  global:
    - GODIR=/go/src/github.com/m-lab/archive-repacker
    - IMAGE=soltesz/archive-repacker:v1.20-testing

before_install:
- go install -v github.com/mattn/goveralls@latest
# Install dependencies, including test dependencies.
- sudo apt-get update
- go get -v -t ./...

script:
# Vet the code, build the code, and run all the tests.
#- go get -u ./...
#- go vet ./...
#- CGO_ENABLED=0 go build ./...
#- go test ./... -race
#- go test ./... -v -coverprofile=_coverage.cov
- travis_wait 40 sh -c 'docker run -w $GODIR -v $PWD:$GODIR -it $IMAGE
   go test -v ./... -race && go test ./... -v -coverprofile=_coverage.cov'


after_success:
# Coveralls
# Upload coverage information for unit tests.
- $HOME/gopath/bin/goveralls -coverprofile=_coverage.cov -service=travis-ci
