timeout: 1800s

options:
  env:
  - PROJECT_ID=$PROJECT_ID

steps:
- name: gcr.io/$PROJECT_ID/golang-cbif:1.20
  id: "Run all unit tests"
  args:
  - go version
  - go get -v -t ./...
  - go test -v -race ./...
  - go test -v ./...

- name: gcr.io/cloud-builders/docker
  id: "Build the job-server docker image"
  args: [
    "build",
      "-t", "gcr.io/$PROJECT_ID/archive-repacker:job-server-${COMMIT_SHA}",
      "-f", "Dockerfile.job-server", "."
  ]

- name: gcr.io/cloud-builders/docker
  id: "Push the job-server docker image to gcr.io"
  args: [
    "push", "gcr.io/$PROJECT_ID/archive-repacker:job-server-${COMMIT_SHA}",
  ]

- name: gcr.io/cloud-builders/docker
  id: "Build the reannotator docker image"
  args: [
    "build",
      "-t", "gcr.io/$PROJECT_ID/archive-repacker:reannotator-${COMMIT_SHA}",
      "-f", "Dockerfile.reannotator", "."
  ]

- name: gcr.io/cloud-builders/docker
  id: "Push the reannotator docker image to gcr.io"
  args: [
    "push", "gcr.io/$PROJECT_ID/archive-repacker:reannotator-${COMMIT_SHA}",
  ]

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy job-server configuration"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -i -e 's/{{COMMIT_SHA}}/'${COMMIT_SHA}'/g' \
           -e 's/{{PROJECT_ID}}/'${PROJECT_ID}'/g' \
           k8s/job-server.yaml
    /builder/kubectl.bash apply -f k8s/job-server.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy reannotator configuration"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -i -e 's/{{COMMIT_SHA}}/'${COMMIT_SHA}'/g' \
           -e 's/{{PROJECT_ID}}/'${PROJECT_ID}'/g' \
           k8s/reannotator.yaml

    /builder/kubectl.bash create configmap reannotator-config \
        --from-file=k8s/reannotator-query.sql --dry-run -o yaml | \
        /builder/kubectl.bash apply -f -

    # Jobs cannot be applied before removing the old one.
    /builder/kubectl.bash delete job reannotator
    /builder/kubectl.bash apply -f k8s/reannotator.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy renamer configuration"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -i -e 's/{{COMMIT_SHA}}/'${COMMIT_SHA}'/g' \
           -e 's/{{PROJECT_ID}}/'${PROJECT_ID}'/g' \
           k8s/renamer.yaml

    # Enable after reannotator has completed.
    /builder/kubectl.bash delete job renamer
    /builder/kubectl.bash apply -f k8s/renamer.yaml
  env:
  - CLOUDSDK_COMPUTE_REGION=$_CLUSTER_REGION
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing
