timeout: 1800s

options:
  env:
  - PROJECT_ID=$PROJECT_ID
  - GIT_COMMIT=$COMMIT_SHA

steps:
- name: gcr.io/$PROJECT_ID/golang-cbif:1.20
  id: "Run all unit tests"
  args:
  - go version
  - go get -v -t ./...
  - go test -v -race
  - go test -v ./...
  env:
  - WORKSPACE_LINK=/go/src/github.com/m-lab/archive-repacker

- name: gcr.io/cloud-builders/docker
  id: "Build the job-server docker image"
  args: [
    "build",
      "-t", "gcr.io/$PROJECT_ID/archive-repacker:job-server-${GIT_COMMIT}",
      "-f", "Dockerfile.job-server", "."
  ]

- name: gcr.io/cloud-builders/kubectl
  id: "Deploy universal gardener configuration"
  entrypoint: /bin/bash
  args:
  - -c
  - |-
    sed -i -e 's/{{GIT_COMMIT}}/'${GIT_COMMIT}'/g' k8s/job-server.yaml
    /builder/kubectl.bash apply --recursive -f k8s/
  env:
  - CLOUDSDK_COMPUTE_REGION=us-east1
  - CLOUDSDK_CONTAINER_CLUSTER=data-processing
