apiVersion: batch/v1
kind: Job
metadata:
  name: reannotator
spec:
  parallelism: 32
  backoffLimit: 128
  template:
    metadata:
      name: reannotator
      labels:
        app: reannotator
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: reannotator
        image: gcr.io/{{PROJECT_ID}}/archive-repacker:reannotator-{{COMMIT_SHA}}
        args:
        - -jobservice.url=http://$(JOB_SERVER_PORT_8083_TCP_ADDR):$(JOB_SERVER_PORT_8083_TCP_PORT)
        - -project={{PROJECT_ID}}
        - -routeview-v4.url=gs://downloader-{{PROJECT_ID}}/RouteViewIPv4/
        - -routeview-v6.url=gs://downloader-{{PROJECT_ID}}/RouteViewIPv6/
        - -asname.url=file:/data/asnames.ipinfo.csv
        - -query=/config/query.sql
        - -prometheusx.listen-address=:9990
        ports:
        - containerPort: 9990

        volumeMounts:
        - name: reannotator-volume
          mountPath: /config
        resources:
          requests:
            cpu: "1"
            memory: "4500Mi"

      volumes:
      - name: reannotator-volume
        configMap:
          name: reannotator-config

      nodeSelector:
        archiver: "true"

      #restartPolicy: OnFailure
      restartPolicy: Never
